name: CD

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "19.x"
      - run: npm install
      - run: npm run build
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: 89.117.9.152
          username: u950298905.prantomain
          password: ${{ secrets.ftp_password }}
          # efsf4444444#R$

      # Only for database, vendor, node_modules
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          username: u950298905
          host: 89.117.9.152
          password: ${{ secrets.ftp_password }}
          port: 65002
          script: |
            cd /home/u950298905/domains/techland360.com/public_html/subdomains/pranto/
            php artisan down
            # cp .env.example .env
            # php artisan key:generate
            php -r "readfile('https://getcomposer.org/installer');" | php -c php.ini
            php composer.phar install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate:fresh --seed
            php artisan storage:link
            php artisan config:clear
            php artisan optimize:clear
            php artisan up
